{
  "hash": "1a65c9e79fbe62dffa52d0044d53404c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"A Paged KV-Cache Allocator, Built from First Principles\"\ndescription: \"An executable simulator for contiguous and paged KV-cache allocation, including fragmentation, copy-on-write, and capacity analysis.\"\nauthor:\n  - name:\n      given: Diego Filippo\n      family: Marino\ndate: \"2026-08-13\"\ncategories: [LLM Serving, Memory Management, Python]\nbibliography: references.bib\njupyter: python3\ndraft: false\n---\n\n## Overview\n\nAutoregressive decoding reuses the keys and values of every previous token. Caching them avoids a full prefix recomputation, but turns serving capacity into a memory-allocation problem: request lengths are unknown, sequences arrive and finish at different times, and branching decoders share long prefixes.\n\nThis project builds a small simulator for two allocation policies:\n\n1. **Contiguous reservation:** reserve each request's declared maximum length.\n2. **Paged allocation:** allocate fixed-size token blocks only when needed.\n\nThe model is intentionally compact. It does not benchmark a GPU kernel. It isolates the allocator mechanism behind PagedAttention and vLLM [@kwon2023pagedattention].\n\n## Cache size\n\nFor a decoder with $L$ layers, $h_{kv}$ key/value heads, head dimension $d_h$, element size $b$ bytes, and $T$ cached tokens, the cache occupies\n\n$$\nB_{KV}=2Lh_{kv}d_hTb.\n$$ {#eq-kv-size}\n\nThe factor two accounts for keys and values. For conventional multi-head attention, $h_{kv}$ equals the query-head count. Multi-query and grouped-query attention reduce $h_{kv}$, which directly reduces the persistent cache.\n\nIt is more useful to read @eq-kv-size as a per-token rate than as a total. Differentiating with respect to $T$ gives $2Lh_{kv}d_hb$ bytes for every token generated, a figure fixed at model-design time:\n\n| Decoder shape | Bytes per cached token | Tokens per GiB | 8K-token request |\n|:--|--:|--:|--:|\n| 32 layers, 32 KV heads, $d_h=128$ | 512 KiB | 2,048 | 4.0 GiB |\n| 32 layers, 8 KV heads, $d_h=128$ | 128 KiB | 8,192 | 1.0 GiB |\n| 80 layers, 8 KV heads, $d_h=128$ | 320 KiB | 3,277 | 2.5 GiB |\n\n: Per-token cache cost at FP16. Grouped-query attention changes the slope, not the shape, of @eq-kv-size. {#tbl-kv-rate}\n\nThe middle row is the reason grouped-query attention is now standard: a four-fold reduction in $h_{kv}$ turns a 4 GiB request into a 1 GiB request with no change to the allocator. The third row is the reason depth is not free at serving time, since layers multiply the cache just as heads do.\n\nThe consequence for scheduling is that cache capacity, not FLOPs, sets the concurrency limit. On an 80 GiB device holding a 140 GiB-class model across two shards, perhaps 20 GiB remains for cache. At the first row's rate that is five concurrent 8K requests; at the second row's rate it is twenty. Equation @eq-kv-size is linear in context length and batch size, which is far better than a quadratic attention matrix, but it is *persistent* rather than transient, and it is allocated and freed at token granularity by requests whose final length nobody knows in advance. That combination, not the size itself, is what makes it an allocator problem.\n\n## Allocation model\n\nA contiguous allocator needs one extent large enough for the request. Reserving the declared maximum avoids relocation while decoding, but unused future slots waste memory. Variable extents also create external fragmentation.\n\nA paged allocator divides the cache into equal physical blocks. Each request owns a logical block table:\n\n$$\n\\text{logical block }j\\longmapsto\\text{physical block }\\pi_r(j).\n$$\n\nThe attention kernel follows this mapping when reading keys and values. Since physical blocks have equal size, they can be taken from a free list and need not be adjacent.\n\n::: {#allocator-source .cell execution_count=1}\n``` {.python .cell-code code-fold=\"false\"}\nfrom dataclasses import dataclass, field\nfrom math import ceil\n\n@dataclass\nclass Request:\n    request_id: int\n    prompt_tokens: int\n    max_tokens: int\n    generated: int = 0\n    blocks: list[int] = field(default_factory=list)\n\n    @property\n    def live_tokens(self):\n        return self.prompt_tokens + self.generated\n\nclass PagedAllocator:\n    def __init__(self, block_count: int, block_tokens: int = 16):\n        self.block_tokens = block_tokens\n        self.free = list(range(block_count))\n\n    def ensure_capacity(self, request: Request):\n        required = ceil(request.live_tokens / self.block_tokens)\n        missing = required - len(request.blocks)\n        if missing > len(self.free):\n            raise MemoryError(\"KV cache exhausted\")\n        for _ in range(missing):\n            request.blocks.append(self.free.pop())\n\n    def release(self, request: Request):\n        self.free.extend(request.blocks)\n        request.blocks.clear()\n```\n:::\n\n\nOnly the final block of a request can be partially empty. If the block contains $B$ token slots, internal waste is bounded by $B-1$ slots per live sequence, independent of maximum generation length.\n\n## A workload experiment\n\nThe following experiment samples 2,000 concurrent requests. Prompt lengths follow a log-normal distribution, maximum generation budgets are deliberately conservative, and actual completions vary. The comparison measures reserved token slots rather than allocator metadata.\n\n::: {#37cf2570 .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\nplt.style.use(\"../../eigenholm.mplstyle\")\n\nrng = np.random.default_rng(11)\nrequests = 2_000\nprompt = np.clip(rng.lognormal(mean=5.2, sigma=0.8, size=requests).astype(int), 16, 4096)\nbudget = rng.choice([128, 256, 512, 1024], size=requests, p=[0.2, 0.35, 0.3, 0.15])\nactual = np.array([rng.integers(1, limit + 1) for limit in budget])\nlive = prompt + actual\nblock_sizes = np.array([8, 16, 32, 64, 128])\n\ncontiguous_reserved = prompt + budget\ncontiguous_efficiency = live.sum() / contiguous_reserved.sum()\npaged_efficiency = np.array([\n    live.sum() / (np.ceil(live / block) * block).sum()\n    for block in block_sizes\n])\n```\n:::\n\n\n::: {#cell-fig-fragmentation .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Plotting code\"}\nfig, ax = plt.subplots(figsize=(7, 3.7))\nax.plot(block_sizes, 100 * paged_efficiency, \"o-\", label=\"paged\")\nax.axhline(100 * contiguous_efficiency, color=\"0.35\", ls=\"--\",\n           label=\"contiguous reservation\")\nax.set(xlabel=\"block size (token slots)\", ylabel=\"live-token efficiency (%)\", ylim=(0, 102))\nax.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Illustrative allocation efficiency under variable request lengths. Paged allocation uses 16-token blocks.](index_files/figure-html/fig-fragmentation-output-1.png){#fig-fragmentation width=968 height=506}\n:::\n:::\n\n\nThese values are simulator outputs, not measurements from the vLLM paper. The qualitative trade-off is real: smaller blocks reduce internal fragmentation but increase block-table entries and kernel address-translation work.\n\n## Allocation under load\n\nThe static comparison above measures a snapshot. It cannot show the failure mode that matters in a serving engine, because that failure mode is temporal: paged allocation lets the scheduler admit a request whose future memory demand has not been reserved. Every admitted request then grows by one block every $B$ decode steps, and the growth is not cancellable. If the cache fills, some request must be evicted and its work discarded.\n\nThe following experiment closes that loop. Requests arrive as a Poisson process, each decode step advances every running request by one token, and admission is greedy under whatever capacity the policy exposes. The paged policy takes one extra parameter: an admission watermark, a fraction of blocks held back so that already-running requests have room to grow.\n\n::: {#911f90cc .cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\"}\nCAPACITY, BLOCK, STEPS, WARMUP = 60_000, 16, 4000, 500\n\ndef simulate(policy, watermark=0.0, arrival_rate=0.6, seed=5):\n    rng = np.random.default_rng(seed)\n    allocator = PagedAllocator(CAPACITY // BLOCK, BLOCK)\n    floor = int(watermark * len(allocator.free))\n    reserved, next_id, completed, preemptions = 0, 0, 0, 0\n    running, queue, target = [], [], {}\n    concurrency, occupancy = [], []\n\n    for _ in range(STEPS):\n        for _ in range(rng.poisson(arrival_rate)):\n            prompt = int(np.clip(rng.lognormal(5.0, 0.8), 16, 2048))\n            budget = int(rng.choice([128, 256, 512, 1024], p=[0.2, 0.35, 0.3, 0.15]))\n            queue.append(Request(next_id, prompt, budget))\n            target[next_id] = int(rng.integers(1, budget + 1))\n            next_id += 1\n\n        while queue:                                    # greedy admission\n            head = queue[0]\n            if policy == \"contiguous\":\n                need = head.prompt_tokens + head.max_tokens\n                if reserved + need > CAPACITY:\n                    break\n                reserved += need\n            else:\n                if ceil(head.live_tokens / BLOCK) > len(allocator.free) - floor:\n                    break\n                allocator.ensure_capacity(head)\n            running.append(queue.pop(0))\n\n        done, evicted = [], []\n        for r in running:                               # one decode step each\n            r.generated += 1\n            if policy == \"paged\":\n                try:\n                    allocator.ensure_capacity(r)\n                except MemoryError:\n                    r.generated -= 1\n                    evicted.append(r)\n                    continue\n            if r.generated >= target[r.request_id]:\n                done.append(r)\n\n        for r in done + evicted:\n            running.remove(r)\n            if policy == \"paged\":\n                allocator.release(r)\n            else:\n                reserved -= r.prompt_tokens + r.max_tokens\n        completed += len(done)\n        for r in evicted:                               # recompute from the prompt\n            preemptions += 1\n            r.generated = 0\n            queue.insert(0, r)\n\n        concurrency.append(len(running))\n        occupancy.append(sum(r.live_tokens for r in running) / CAPACITY)\n\n    return dict(completed=completed, preemptions=preemptions, queued=len(queue),\n                concurrency=np.mean(concurrency[WARMUP:]),\n                occupancy=np.mean(occupancy[WARMUP:]))\n\nbaseline = simulate(\"contiguous\")\nwatermarks = [0.0, 0.02, 0.05, 0.10, 0.20]\nruns = [simulate(\"paged\", w) for w in watermarks]\n\ncompleted = np.array([r[\"completed\"] for r in runs])\noccupancy = np.array([r[\"occupancy\"] for r in runs])\nthrash = np.array([r[\"preemptions\"] / max(r[\"completed\"], 1) for r in runs])\npct = 100 * np.array(watermarks)\n```\n:::\n\n\n::: {#cell-fig-admission-watermark .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Plotting code\"}\nfig, axes = plt.subplots(1, 2, figsize=(8.8, 3.5))\naxes[0].plot(pct, completed, \"o-\", label=\"paged\")\naxes[0].axhline(baseline[\"completed\"], color=\"0.35\", ls=\"--\",\n                label=\"contiguous reservation\")\naxes[0].set(xlabel=\"blocks held back at admission (%)\",\n            ylabel=\"requests completed\", title=\"Goodput\")\naxes[0].legend()\n\noccupancy_line, = axes[1].plot(pct, 100 * occupancy, \"o-\", label=\"paged occupancy\")\naxes[1].axhline(100 * baseline[\"occupancy\"], color=\"0.35\", ls=\"--\",\n                label=\"contiguous occupancy\")\naxes[1].set(xlabel=\"blocks held back at admission (%)\",\n            ylabel=\"live-token occupancy (%)\", title=\"Occupancy and thrashing\")\nthrash_axis = axes[1].twinx()\nthrash_line, = thrash_axis.semilogy(pct, np.maximum(thrash, 1e-3), \"s:\", color=\"0.25\",\n                                    label=\"preemptions per completion\")\nthrash_axis.set(ylabel=\"preemptions per completion\", ylim=(5e-4, 5e2))\nthrash_axis.spines[\"right\"].set_visible(True)   # this panel does use a second y axis\naxes[1].legend(handles=[occupancy_line, thrash_line], fontsize=7,\n               loc=\"center right\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Discrete-event simulation of 4,000 decode steps against a 60,000-token cache. Paging alone raises occupancy but admits requests it cannot sustain; holding back a small block reserve at admission converts that occupancy into completed work.](index_files/figure-html/fig-admission-watermark-output-1.png){#fig-admission-watermark width=1220 height=478}\n:::\n:::\n\n\n::: {#e9a50fac .cell execution_count=6}\n``` {.python .cell-code code-fold=\"false\"}\nprint(f\"contiguous: {baseline['completed']} completed, \"\n      f\"{baseline['concurrency']:.0f} concurrent, \"\n      f\"{100 * baseline['occupancy']:.0f}% occupancy, {baseline['queued']} queued\")\nfor w, r in zip(watermarks, runs):\n    print(f\"paged @ {100 * w:4.0f}% watermark: {r['completed']} completed, \"\n          f\"{r['concurrency']:.0f} concurrent, {100 * r['occupancy']:.0f}% occupancy, \"\n          f\"{r['preemptions']} preemptions, {r['queued']} queued\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncontiguous: 1356 completed, 72 concurrent, 50% occupancy, 1023 queued\npaged @    0% watermark: 1300 completed, 179 concurrent, 85% occupancy, 83017 preemptions, 930 queued\npaged @    2% watermark: 2308 completed, 130 concurrent, 90% occupancy, 17 preemptions, 16 queued\npaged @    5% watermark: 2304 completed, 129 concurrent, 89% occupancy, 0 preemptions, 27 queued\npaged @   10% watermark: 2253 completed, 126 concurrent, 87% occupancy, 0 preemptions, 75 queued\npaged @   20% watermark: 2056 completed, 114 concurrent, 78% occupancy, 0 preemptions, 285 queued\n```\n:::\n:::\n\n\nThe result is worth stating carefully, because the naive reading of paging is wrong.\n\nAt a zero watermark, paging does exactly what the static experiment promised. Mean concurrency rises from 72 requests to 179, and live-token occupancy rises from 50 percent to 85 percent. Goodput nevertheless *falls below the contiguous baseline*. The allocator admits requests until the cache is nearly full, every survivor keeps demanding one more block, and the system spends its decode steps evicting and restarting work: over eighty thousand preemptions to produce thirteen hundred completions.\n\nHolding back two percent of blocks removes the pathology entirely. Concurrency settles at 130 rather than 179, occupancy reaches 90 percent, preemptions fall to seventeen, and completions rise to 2,308: roughly 1.7 times the contiguous baseline, with the arrival backlog cleared rather than growing without bound. Larger watermarks decay gracefully, trading a few points of occupancy for nothing in return.\n\nTwo lessons generalize beyond the simulator. First, occupancy is not goodput. A memory system can be nearly full of tokens that will be thrown away. Second, paging does not remove the admission decision, it relocates it. Contiguous reservation answers \"can this request ever fit?\" pessimistically and permanently at admission time; paging answers it optimistically and repeatedly at every decode step, which is only safe if the scheduler keeps a margin for the growth it has already committed to. The vLLM watermark, the maximum-batched-token limits in production servers, and continuous-batching admission control all exist for this reason.\n\n## Prefix sharing and copy-on-write\n\nPaging makes sharing natural. Parallel samples from one prompt can point their logical prefix blocks to the same physical blocks. Maintain a reference count $c_b$ for every physical block. A fork increments counts; releasing a request decrements them.\n\nAppending to a shared partially filled block requires copy-on-write:\n\n```python\ndef append_with_cow(request, refcount, free_blocks, block_tokens):\n    last = request.blocks[-1]\n    offset = request.live_tokens % block_tokens\n    if offset and refcount[last] > 1:\n        replacement = free_blocks.pop()\n        copy_block(last, replacement)  # device-to-device copy\n        refcount[last] -= 1\n        refcount[replacement] = 1\n        request.blocks[-1] = replacement\n    append_token_kv(request.blocks[-1], offset)\n```\n\nFull shared prefix blocks never need copying. Only the block currently being extended can trigger copy-on-write. This supports parallel sampling, beam search, and shared system prompts with the same mechanism.\n\n## Scheduling consequences\n\nBetter allocation increases the feasible batch size, but the watermark experiment shows that the allocator cannot be evaluated apart from the policy that drives it. A production server must also decide which requests enter a batch and how to recover under pressure.\n\nRecovery has two standard forms, and the choice interacts with block size. Swapping cache blocks to host memory preserves completed work but consumes interconnect bandwidth proportional to the evicted request's live tokens. Recomputation discards the blocks and rebuilds them with one prefill pass, trading compute for storage; it is usually preferred for short prefixes because prefill is parallel across positions while a swap is serial in bandwidth. The simulation above models the recomputation branch, which is why a preempted request restarts from `generated = 0` rather than resuming.\n\nEviction granularity matters too. Evicting one request frees $\\lceil T/B\\rceil$ blocks at once, so a scheduler under pressure has a coarse, lumpy lever: it cannot free a little memory, only a whole sequence. This is the practical argument for admission control over eviction. Refusing to start work is cheap, whereas stopping work that is already underway wastes everything spent on it.\n\nThe vLLM paper reports near-zero KV-cache waste and 2 to 4 times higher throughput at comparable latency than the evaluated baselines [@kwon2023pagedattention]. The gain comes from the system built around the allocator, not address translation alone. Larger effective batches improve GPU utilization, while prefix sharing avoids duplicate storage.\n\n## Verification targets\n\nA serious allocator test suite should exercise:\n\n- allocation across non-contiguous physical blocks;\n- release and reuse without stale references;\n- forked prefixes with correct reference counts;\n- copy-on-write only for a shared writable tail;\n- out-of-memory behavior that leaves existing tables unchanged;\n- block-table translation against a contiguous reference implementation.\n\nThe last test is especially important. PagedAttention changes where tensors live, not the mathematical output of attention.\n\n## Limitations\n\nThis simulator counts token slots. Real systems allocate per layer, shard tensors across devices, align blocks for kernels, and synchronize allocator state with asynchronous execution. Kernel layout can also favor a block size that is not optimal under a pure fragmentation metric.\n\nStill, the model captures the essential systems insight: once persistent state has irregular lifetimes, a tensor is not only a numerical object. It is also a dynamically allocated resource.\n\n## Related reading\n\n- [FlashAttention Is an IO Algorithm](../../posts/flashattention-io-aware/index.qmd) makes the case for treating attention as a memory problem.\n- [The Rank of Memory](../../posts/rank-of-memory/index.qmd) asks what the cache is buying in the first place.\n- [Speculative Sampling Preserves the Target Distribution](../../notes/speculative-sampling/index.qmd) adds sequences that this allocator has to hold.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}